name: floatingobjects
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - gdal
  - rasterio
  - shapely
  - geopandas
  - numpy
  - pip:
    - torch
    - opencv-python
    - scikit-learn
    - scikit-image
    - matplotlib
    - tqdm
    - pandas
    - tensorboard
    - rio-cogeo
    - gdown
    - segmentation-models-pytorch
